name: Typescript
on:
  repository_dispatch:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Create spec json
        id: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "openapi.json"
          json: ${{ github.event.client_payload.pkg_spec }}

      - name: Setup openapi config
        run: |
          export SDK_PKG_NAME=${{ github.event.client_payload.pkg_name }}
          envsubst < config/typescript.yml> typescript-axios-config.yml

      - name: Generate typescript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          config-file: typescript-axios-config.yml
          generator-tag: v6.2.1
          command-args: --git-host github.com --git-user-id timada-org --git-repo-id ${{ github.event.client_payload.pkg_name }}

      - name: Publish
        run: |
          cd typescript-axios-client
          jq -M '. + {name:"@timada/${{ github.event.client_payload.pkg_name }}-client", license:"APACHE-2.0", files:["dist"]}' package.json > package.json.tmp && mv package.json.tmp package.json
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm install
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
