name: Typescript
on: pull_request

env:
  SDK_PKG_NAME: cobase
  SDK_PKG_SPEC: '{"openapi":"3.0.3","info":{"title":"api","description":"","contact":{"name":""},"license":{"name":""},"version":"0.0.1"},"paths":{"/groups":{"get":{"tags":["group"],"description":"","operationId":"find_all","responses":{"200":{"description":"Get groups did not result error","content":{"application/json":{"schema":{"type":"array","items":{"$ref":"#/components/schemas/Group"}}}}}},"deprecated":false}},"/groups/create":{"post":{"tags":["group"],"description":"","operationId":"create","requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/CreateCommand"}}},"required":true},"responses":{"200":{"description":"Create group did not result error","content":{"application/json":{"schema":{"type":"array","items":{"$ref":"#/components/schemas/Group"}}}}}},"deprecated":false}}},"components":{"schemas":{"CreateCommand":{"type":"object","required":["name"],"properties":{"name":{"type":"string"}}},"Group":{"type":"object","required":["name"],"properties":{"name":{"type":"string","example":"Transquadra"}}}}}}'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Setup openapi config
        run: |
          echo "$SDK_PKG_SPEC" > openapi.json
          envsubst < config/typescript.yml> typescript-axios-config.yml

      - name: Generate typescript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          config-file: typescript-axios-config.yml
          generator-tag: v6.2.1
          command-args: --git-host gitlab.com --git-user-id timada-org --git-repo-id sdk

      - name: Install dependencies
        run: |
          cd typescript-axios-client
          sed -i -r 's/"name": "(.*)"/"name": "@timada\/\1"/g' package.json
          sed -i 's/Unlicense/APACHE-2.0/g' package.json
          cat package.json
          npm install
          npm run build
          find . -type f -name '*.ts' -name '*.sh' -delete
          rm -rf node_modules package-lock.json tsconfig*
          ls -al
